[package]
name = "assembler-rs"
version = "0.1.0"
authors = ["kanno"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
